# 03 - Data Quality Assessment

## Goal

The goal of this notebook is to assess the quality of the raw StatsBomb event dataset by examining its structure, data types, missing values, and duplicate records before performing task-specific preprocessing in later stages of the project.

## Import Libraries

In [3]:
import pandas as pd
import numpy as np

## Load Dataset

In [4]:
events_df = pd.read_csv("../data/raw/fawsl_events.csv")

C:\Users\Korisnik\AppData\Local\Temp\ipykernel_9356\1013803508.py:1: DtypeWarning: Columns (0: bad_behaviour_card, 1: ball_recovery_offensive, 2: block_offensive, 3: dribble_nutmeg, 4: dribble_overrun, 5: foul_committed_advantage, 6: foul_committed_card, 7: foul_committed_type, 8: foul_won_advantage, 9: goalkeeper_shot_saved_to_post, 10: injury_stoppage_in_chain, 11: pass_deflected, 12: pass_straight, 13: shot_one_on_one, 14: shot_open_goal, 15: shot_saved_to_post, 16: block_deflection, 17: miscontrol_aerial_won, 18: pass_outswinging, 19: shot_deflected, 20: goalkeeper_shot_saved_off_target, 21: pass_miscommunication, 22: pass_no_touch, 23: shot_redirect, 24: shot_saved_off_target, 25: clearance_other, 26: foul_committed_offensive, 27: dribble_no_touch, 28: block_save_block, 29: foul_committed_penalty, 30: foul_won_penalty, 31: player_off_permanent, 32: goalkeeper_lost_out, 33: goalkeeper_punched_out, 34: goalkeeper_success_out, 35: goalkeeper_success_in_play, 36: goalkeeper_penalty_saved_to_post) have mixed types. Specify dtype option on import or set low_memory=False.
  events_df = pd.read_csv("../data/raw/fawsl_events.csv")

## Explore Dataset

In [5]:
events_df.shape

(495189, 115)

In [6]:
events_df.head()

,50_50,bad_behaviour_card,ball_receipt_outcome,ball_recovery_offensive,ball_recovery_recovery_failure,block_offensive,carry_end_location,clearance_aerial_won,clearance_body_part,clearance_head,...,dribble_no_touch,block_save_block,foul_committed_penalty,foul_won_penalty,player_off_permanent,goalkeeper_lost_out,goalkeeper_punched_out,goalkeeper_success_out,goalkeeper_success_in_play,goalkeeper_penalty_saved_to_post
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
events_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 495189 entries, 0 to 495188
Columns: 115 entries, 50_50 to goalkeeper_penalty_saved_to_post
dtypes: float64(8), int64(8), object(54), str(45)
memory usage: 434.5+ MB

In [8]:
events_df.describe()

,duration,index,match_id,minute,pass_angle,pass_length,pass_recipient_id,period,player_id,possession,possession_team_id,second,shot_statsbomb_xg,substitution_outcome_id,substitution_replacement_id,team_id
count,367791.000000,495189.000000,4.951890e+05,495189.000000,133573.000000,133573.000000,127525.000000,495189.000000,492845.000000,495189.000000,495189.000000,495189.000000,3529.000000,1080.000000,1080.000000,495189.000000
mean,1.245234,1884.262918,3.913082e+06,46.389084,0.004331,19.912256,62246.567489,1.495435,63638.492595,91.913609,1255.374087,29.217578,0.111394,102.930556,96747.224074,1256.264606
std,1.375868,1096.724345,1.531607e+02,27.780465,1.577903,12.261760,93073.453628,0.499980,94126.684974,54.406484,651.335653,17.373798,0.131714,0.254326,127601.482911,651.193790
min,0.000000,1.000000,3.912592e+06,0.000000,-3.137460,0.000000,4636.000000,1.000000,4636.000000,1.000000,746.000000,0.000000,0.000180,102.000000,4636.000000,746.000000
25%,0.265459,938.000000,3.913090e+06,23.000000,-1.199278,11.395174,15571.000000,1.000000,15577.000000,45.000000,965.000000,14.000000,0.039145,103.000000,16374.000000,965.000000
50%,1.028835,1876.000000,3.913122e+06,46.000000,-0.008368,16.977926,25632.000000,1.000000,25632.000000,90.000000,968.000000,29.000000,0.067797,103.000000,31563.000000,968.000000
75%,1.722711,2814.000000,3.913155e+06,69.000000,1.220482,25.204960,47008.000000,2.000000,47521.000000,137.000000,1475.000000,44.000000,0.123585,103.000000,112522.000000,1475.000000
max,47.705833,4543.000000,3.913188e+06,107.000000,3.141593,111.216190,432915.000000,2.000000,432915.000000,231.000000,2652.000000,59.000000,0.957107,103.000000,432915.000000,2652.000000

## Assess Missing Values

In [9]:
events_df.isnull().sum()

50_50                               494224
bad_behaviour_card                  495094
ball_receipt_outcome                472968
ball_recovery_offensive             495139
ball_recovery_recovery_failure      493825
                                     ...
goalkeeper_lost_out                 495187
goalkeeper_punched_out              495178
goalkeeper_success_out              495188
goalkeeper_success_in_play          495186
goalkeeper_penalty_saved_to_post    495188
Length: 115, dtype: int64

In [10]:
missing = (
    events_df
    .isnull()
    .sum()
    .sort_values(ascending=False)
)

missing

goalkeeper_success_out              495188
goalkeeper_penalty_saved_to_post    495188
player_off_permanent                495187
goalkeeper_lost_out                 495187
shot_redirect                       495186
                                     ...
possession                               0
type                                     0
timestamp                                0
team                                     0
team_id                                  0
Length: 115, dtype: int64

In [11]:
missing_percentage = (
    events_df
    .isnull()
    .mean()
    .mul(100)
    .round(2)
    .sort_values(ascending=False)
)

missing_percentage

goalkeeper_shot_saved_to_post       100.0
goalkeeper_penalty_saved_to_post    100.0
shot_saved_to_post                  100.0
foul_committed_penalty              100.0
shot_saved_off_target               100.0
                                    ...
possession                            0.0
type                                  0.0
timestamp                             0.0
team                                  0.0
team_id                               0.0
Length: 115, dtype: float64

In [12]:
high_missing = missing_percentage[missing_percentage > 90]

high_missing

goalkeeper_shot_saved_to_post       100.00
goalkeeper_penalty_saved_to_post    100.00
shot_saved_to_post                  100.00
foul_committed_penalty              100.00
shot_saved_off_target               100.00
                                     ...
duel_type                            98.16
counterpress                         96.68
ball_receipt_outcome                 95.51
pass_type                            94.86
pass_outcome                         94.28
Length: 86, dtype: float64

## Check for Duplicate Records

In [13]:
events_df.duplicated().sum()

np.int64(0)

## Inspect Data Types

In [14]:
events_df.dtypes

50_50                                  str
bad_behaviour_card                     str
ball_receipt_outcome                   str
ball_recovery_offensive             object
ball_recovery_recovery_failure      object
                                     ...
goalkeeper_lost_out                 object
goalkeeper_punched_out              object
goalkeeper_success_out              object
goalkeeper_success_in_play          object
goalkeeper_penalty_saved_to_post    object
Length: 115, dtype: object

## Dataset Validation

In [15]:
events_df["type"].nunique()

33

In [17]:
sorted(events_df["type"].unique())

['50/50',
 'Bad Behaviour',
 'Ball Receipt*',
 'Ball Recovery',
 'Block',
 'Carry',
 'Clearance',
 'Dispossessed',
 'Dribble',
 'Dribbled Past',
 'Duel',
 'Error',
 'Foul Committed',
 'Foul Won',
 'Goal Keeper',
 'Half End',
 'Half Start',
 'Injury Stoppage',
 'Interception',
 'Miscontrol',
 'Offside',
 'Own Goal Against',
 'Own Goal For',
 'Pass',
 'Player Off',
 'Player On',
 'Pressure',
 'Referee Ball-Drop',
 'Shield',
 'Shot',
 'Starting XI',
 'Substitution',
 'Tactical Shift']

In [18]:
events_df["match_id"].nunique()

132

## Conclusion

The raw event dataset was successfully validated. No duplicate records were detected, while the large number of missing values is expected due to the event-based structure of StatsBomb data, where different event types contain different attributes. Therefore, no missing values were removed or imputed at this stage. Further preprocessing will be performed after selecting the event types relevant to the research objectives.